AWSTemplateFormatVersion: 2010-09-09

Description: Empty all contents from a specified s3 bucket.

Parameters: 

  GlobalTag:
    Type: String
    Description: >
      A common value that all resources in this template will have prefixed to
      their name and attached as a tag to establish a bundling through naming convention. If a nested stack,
      this will most likely be the name of the top-most stack.
    Default: kuali-alb
    
  Service:
    Description: Service catalog name
    Type: String
    Default: research-administration

  Function:
    Description: The Function within the Service
    Type: String
    Default: kuali

  Landscape:
    Description: Specify a name for your landscape
    Type: String
    AllowedPattern: "[a-zA-Z\\d]{1,12}"
    ConstraintDescription: Up to 12 letters and/or numbers
  
  TemplateBucketName:
    Type: String
    Description: The S3 bucket kuali research cloudformation templates, config files, keys, etc. are stored
    Default: kuali-conf

  RetainLogs:
    Type: String
    Description: Indicate if the logs produced by the lambda function should survive stack deletion.
    Default: "false"
    AllowedValues:
    - "true"
    - "false"
    ConstraintDescription: Enter "true" or "false" only.


Conditions:
  retainLogs: !Equals [!Ref RetainLogs, 'true']
  deleteLogs: !Equals [!Ref RetainLogs, 'false']


Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: !Sub ${GlobalTag}-${Landscape}-empty-s3-bucket-delete
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:ListBucket
            - s3:DeleteObject
            - s3:DeleteObjects
            Resource:
            - !Sub arn:aws:s3:::${GlobalTag}-${Landscape}*
            - !Sub arn:aws:s3:::${GlobalTag}-${Landscape}*/*
      - PolicyName: !Sub ${GlobalTag}-${Landscape}-empty-s3-bucket-cloudwatch
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            # - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"
      # ManagedPolicyArns:
      # - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        
  # DeletionPolicy & DependsOn cannot use conditions - must be a raw string. Therefore you have to move the conditional
  # up to the resource Condition attribute and create one of two resource sets depending on your deletion policy preference.

  # A) Retain logs after lambda that created them is deleted.
  LambdaLogsGroupRetain:
    Type: AWS::Logs::LogGroup
    Condition: retainLogs
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${GlobalTag}-${Landscape}-bucket-emptier
      RetentionInDays: 30  
  EmptyBucketLoggingLambdaA:
    Type: AWS::Lambda::Function
    Condition: retainLogs
    DependsOn: LambdaLogsGroupRetain
    Properties:
      Description: !Sub 
      - Empty all contents from a specified s3 bucket (LogGroup - ${loggroup}).
      - loggroup: LambdaLogsGroupRetain.Arn
      Handler: bucket_emptier.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs12.x
      Timeout: 600  # 10 minutes
      FunctionName: !Sub ${GlobalTag}-${Landscape}-bucket-emptier
      Code:
        S3Bucket: !Ref TemplateBucketName
        S3Key: cloudformation/kuali_lambda/bucket_emptier.zip

  # Or...

  # B) Delete logs along with the lambda that created them.

  LambdaLogsGroupDelete:
    Type: AWS::Logs::LogGroup
    Condition: deleteLogs
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub /aws/lambda/${GlobalTag}-${Landscape}-bucket-emptier
      RetentionInDays: 30
  EmptyBucketLoggingLambdaB:
    Type: AWS::Lambda::Function
    Condition: deleteLogs
    DependsOn: LambdaLogsGroupDelete
    Properties:
      Description: !Sub 
      - Empty all contents from a specified s3 bucket (LogGroup - ${loggroup}).
      - loggroup: LambdaLogsGroupDelete.Arn
      Handler: bucket_emptier.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs12.x
      Timeout: 600  # 10 minutes
      FunctionName: !Sub ${GlobalTag}-${Landscape}-bucket-emptier
      Code:
        S3Bucket: !Ref TemplateBucketName
        S3Key: cloudformation/kuali_lambda/bucket_emptier.zip

Outputs:

  LambdaArn:
    Value:
      !If
        - deleteLogs
        - !GetAtt EmptyBucketLoggingLambdaB.Arn
        - !GetAtt EmptyBucketLoggingLambdaA.Arn
