AWSTemplateFormatVersion: 2010-09-09

Description: Empty all contents from a specified s3 bucket.

Parameters: 

  GlobalTag:
    Type: String
    Description: >
      A common value that all resources in this template will have prefixed to
      their name and attached as a tag to establish a bundling through naming convention. If a nested stack,
      this will most likely be the name of the top-most stack.
    Default: kuali-alb
    
  Service:
    Description: Service catalog name
    Type: String
    Default: research-administration

  Function:
    Description: The Function within the Service
    Type: String
    Default: kuali

  Landscape:
    Description: Specify which landscape to build into the VPC
    Type: String
    AllowedValues:
    - sb
    - ci
    - qa
    - stg
    - prod
    ConstraintDescription: >
      This parameter is restricted to the following values: sb, ci, qa, stg, prod
    Default: sb
  
  TemplateBucketName:
    Type: String
    Description: The S3 bucket kuali research cloudformation templates, config files, keys, etc. are stored
    Default: kuali-conf


Resources:

  LambdaAlbExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: empty-s3-bucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:ListBucket
            - s3:DeleteObject
            - s3:DeleteObjects
            Resource:
            - !Sub arn:aws:s3:::${GlobalTag}-${Landscape}*
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # Should get called during stack delete, see: 
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-requesttypes-delete.html
  ToggleAlbLoggingLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Empty all contents from a specified s3 bucket.
      Handler: bucket_emptier.handler
      Role: !GetAtt WafLambdaExecutionRole.Arn
      Runtime: nodejs12.x
      Timeout: 600  # 10 minutes
      FunctionName: !Sub ${GlobalTag}-${Landscape}-bucket-emptier
      Code:
        S3Bucket: !Ref TemplateBucketName
        S3Key: cloudformation/kuali_lambda/bucket_emptier/bucket_emptier.zip

Outputs:

  LambdaArn:
    Value:
      !GetAtt ToggleAlbLoggingLambda.Arn
