AWSTemplateFormatVersion: 2010-09-09


Description: >
  This stack comprises a role set up for access by a lambda function in another account to 
  assume so as to push docker images from the ecr in that account to the ecr in this account.
  Create the stack in the trusting (target) account.
  
Parameters:

  Service:
    Description: Service catalog name.
    Type: String
    Default: research-administration

  Function:
    Description: The Function within the Service.
    Type: String
    Default: kuali

  Landscape:
    Description: Specify a name for your landscape
    Type: String
    AllowedPattern: "[a-zA-Z\\d]{1,12}"
    ConstraintDescription: Up to 12 letters and/or numbers
    Default: empty
  
  TrustedAccount:
    Type: String
    Description: The id of the trusted account
    Default: 770203350335
  
  TrustedRoleName:
    Type: String
    Description: The name of the trusted role from the trusted account
    Default: kuali-ecr-sync-trusted-role


Conditions:

  IsLandscapeProvided: !Not [ !Equals [ !Ref Landscape, empty ] ]
  IsDefaultTrustedRoleName: !Equals [ !Ref TrustedRoleName, kuali-ecr-sync-trusted-role ]
  # The role name is still based on the default and is only "custom" in that it has the landscape value injected into it.
  CustomTrustedRoleName: !And [ Condition: IsDefaultTrustedRoleName, Condition: IsLandscapeProvided ]

Resources:

  CrossAccountAssumableRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: kuali-ecr-sync-trusting-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        # Commenting out due to issue warned about in: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html#principal-roles
        # Statement:
        #   - Effect: Allow
        #     Principal:
        #       AWS: 
        #         - 
        #           !If 
        #             - CustomTrustedRoleName
        #             - !Sub arn:aws:iam::${TrustedAccount}:role/kuali-${Landscape}-ecr-sync-trusted-role
        #             - !Sub arn:aws:iam::${TrustedAccount}:role/${TrustedRoleName}
        #         - !Sub arn:aws:iam::${TrustedAccount}:root
        #     Action: sts:AssumeRole

        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                - !Sub arn:aws:iam::${TrustedAccount}:root
            Condition:
              ArnEquals:
                aws:PrincipalArn: 
                  !If 
                    - CustomTrustedRoleName
                    - !Sub arn:aws:iam::${TrustedAccount}:role/kuali-${Landscape}-ecr-sync-trusted-role
                    - !Sub arn:aws:iam::${TrustedAccount}:role/${TrustedRoleName}
            Action: sts:AssumeRole

      Path: /
      Policies:
        - PolicyName: kuali-ecr-sync-trusting-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudtrail:LookupEvents'
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecr:*
                Resource:
                  # Legacy
                  - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/coeus
                  - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/coeus-feature
                  - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/core
                  - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/core-feature
                  - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/portal
                  - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/portal-feature
                  - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/research-pdf
                  # CSS
                  - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/kuali-coeus
                  - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/kuali-coeus-feature
                  - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/kuali-core
                  - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/kuali-core-feature
                  - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/kuali-portal
                  - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/kuali-portal-feature
                  - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/kuali-research-pdf
                  - !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/research-admin-reports
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:CreateServiceLinkedRole
                Resource: "*"
                Condition:
                  StringEquals:
                    iam:AWSServiceName:
                      - replication.ecr.amazonaws.com

Outputs:

  RoleArn:
    Description: > 
      The arn of the role created here in the target account. 
      Reference this arn in the trust policy for the ec2 instance in the source account.
    Value:
      !GetAtt CrossAccountAssumableRole.Arn