AWSTemplateFormatVersion: '2010-09-09'

# References:
# https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/CreatingNewSubdomain.html
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Route53.html
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-route53.html
# https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DomainNameFormat.html

# NOTE ON SECURITY:
# Currently the database dns name is a subdomain of the main kuali domain name (example: stg.db.kuali.research.bu.edu or db.kuali.research.bu.edu).
# The resolved IP address can only be reached by application servers sitting in adjacent subnets as the RDS instance in the same vpc or from desktop
# clients as long as they are logged into the bu dbreport vpn (due to security group restrictions).
# However, if the security requirements ever require it to be necessary to restrict database dns resolution itself to on-campus/internal requests,
# Then a separate, private hosted zone would need to be created for the database alone.
# RELATED: https://aws.amazon.com/premiumsupport/knowledge-center/route53-resolve-with-inbound-endpoint/

Description: Deploy a hosted zone to handle delegated dns resolution requests for kuali application and database endpoints.

Parameters:

  GlobalTag:
    Type: String
    Description: >
      A common value that all resources in this template will have prefixed to
      their name and attached as a tag to establish a bundling through naming convention. If a nested stack,
      this will most likely be the name of the top-most stack.
    Default: kuali-dns
    
  Service:
    Description: Service catalog name
    Type: String
    Default: research-administration

  Function:
    Description: The Function within the Service
    Type: String
    Default: kuali

  DomainName:
    Description: The domain name for the hosted zone
    Type: String
    Default: kuali.research.bu.edu

  CreateHostedZoneLogGroup:
    Description: Log activity for the app hosted zone to cloudwatch?
    Type: String
    Default: "yes"
    AllowedValues:
    - "yes"
    - "no"

  HostedZoneLoggingPolicyName:
    Description: Log activity for the app hosted zone to cloudwatch?
    Type: String
    Default: "empty"


Conditions:
    CreateLogGroup: !Equals [!Ref CreateHostedZoneLogGroup, 'yes']
    CreateLoggingPolicy: !And [ Condition: CreateLogGroup, !Not [!Equals [!Ref HostedZoneLoggingPolicyName, 'empty']]]


Resources:

  # This won't work. You must manually created a resouce-based policy first.
  # Route53 is a service that, for logging, supports attaching permission policies to it as a resource, not a principal.
  # This means that route53 does not assume a role that grants it permission to log to cloudwatch, but the route53 
  # resource itself is associated with the policy that the role would have had.
  # SEE: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_compare-resource-policies.html
  #
  # CloudwatchLoggingRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Statement:
  #       - Effect: Allow
  #         Principal:
  #           Service: route53.amazonaws.com
  #         Action: sts:AssumeRole
  #     Policies:
  #     - PolicyName: CloudWatchAccess
  #       PolicyDocument:
  #         Statement:
  #           - Effect: Allow
  #             Action:
  #               - logs:PutLogEvents
  #               - logs:CreateLogStream
  #             Resource: !GetAtt HostedZoneLogGroup.Arn

  CloudwatchLoggingResourcePolicy:
    Type: AWS::Logs::ResourcePolicy
    DeletionPolicy: Retain
    Condition: CreateLoggingPolicy
    Properties:
      PolicyName: !Ref HostedZoneLoggingPolicyName
      PolicyDocument: !Sub "{
        \"Version\": \"2012-10-17\", 
        \"Statement\": [
            {
              \"Effect\": \"Allow\",
              \"Principal\": {
                \"Service\": \"route53.amazonaws.com\"
              },
              \"Action\": [
                \"logs:PutLogEvents\",
                \"logs:CreateLogStream\"
              ],
              \"Resource\": \"arn:aws:logs:us-east-1:${AWS::AccountId}:log-group:/aws/route53/*\"
            }
          ]
        }"

  HostedZoneLogGroup:
    Type: AWS::Logs::LogGroup
    Condition: CreateLogGroup
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub /aws/route53/${GlobalTag}-hosted-zone
      RetentionInDays: 30

  DNS: 
    Type: AWS::Route53::HostedZone
    Properties: 
      Name: !Ref DomainName
      HostedZoneConfig: 
        Comment: !Sub Hosted zone for ${DomainName}
      QueryLoggingConfig:
        CloudWatchLogsLogGroupArn: !GetAtt HostedZoneLogGroup.Arn
      HostedZoneTags: 
        - Key: Name
          Value: !Sub ${GlobalTag}-hosted-zone
        - Key: Service
          Value: !Ref Service
        - Key: Function
          Value: !Ref Function
