AWSTemplateFormatVersion: 2010-09-09

Description: Toggle logging for an application load balancer.

Parameters: 

  GlobalTag:
    Type: String
    Description: >
      A common value that all resources in this template will have prefixed to
      their name and attached as a tag to establish a bundling through naming convention. If a nested stack,
      this will most likely be the name of the top-most stack.
    Default: kuali-alb
    
  Service:
    Description: Service catalog name
    Type: String
    Default: research-administration

  Function:
    Description: The Function within the Service
    Type: String
    Default: kuali

  Landscape:
    Description: Specify a name for your landscape
    Type: String
    AllowedPattern: "[a-zA-Z\\d]{1,12}"
    ConstraintDescription: Up to 12 letters and/or numbers
  
  TemplateBucketName:
    Type: String
    Description: The S3 bucket kuali research cloudformation templates, config files, keys, etc. are stored
    Default: kuali-conf

  RetainLogs:
    Type: String
    Description: Indicate if the logs produced by the lambda function should survive stack deletion.
    Default: "false"
    AllowedValues:
    - "true"
    - "false"
    ConstraintDescription: Enter "true" or "false" only.


Conditions:
  retainLogs: !Equals [!Ref RetainLogs, 'true']
  deleteLogs: !Equals [!Ref RetainLogs, 'false']


Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      # - PolicyName: !Sub ${GlobalTag}-${Landscape}-lambda-logging
      #   PolicyDocument:
      #     Version: '2012-10-17'
      #     Statement:
      #     - Effect: Allow
      #       Action:
      #       - logs:*
      #       Resource: arn:aws:logs:*:*:*
      - PolicyName: !Sub ${GlobalTag}-${Landscape}-alb-toggle-logging-execution
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - elasticloadbalancing:Describe*
            - elasticloadbalancing:ModifyLoadBalancerAttributes
            Resource:
            - !Sub arn:aws:elasticloadbalancing:::loadbalancer/${GlobalTag}-${Landscape}*
          - Effect: Allow
            Action:
            - tag:Get*
            Resource:
            - "*"            
      - PolicyName: !Sub ${GlobalTag}-${Landscape}-alb-toggle-logging-cloudwatch
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            # - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"
      # ManagedPolicyArns:
      # - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaLogsGroupTemp:
    Type: AWS::Logs::LogGroup
    Condition: deleteLogs
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub /aws/lambda/${GlobalTag}-${Landscape}-alb-logging-toggler
      RetentionInDays: 30
  LambdaLogsGroup:
    Type: AWS::Logs::LogGroup
    Condition: retainLogs
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${GlobalTag}-${Landscape}-alb-logging-toggler
      RetentionInDays: 30

  # Should get called during stack delete, see: 
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-requesttypes-delete.html
  ToggleAlbLoggingLambda:
    Type: AWS::Lambda::Function
    DependsOn: LambdaLogsGroup
    Properties:
      Description: Turn off logging for the specified ALB.
      Handler: toggle_alb_logging.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs12.x
      Timeout: 15  # 15 seconds
      FunctionName: !Sub ${GlobalTag}-${Landscape}-alb-logging-toggler
      Code:
        S3Bucket: !Ref TemplateBucketName
        S3Key: cloudformation/kuali_lambda/toggle_alb_logging.zip

Outputs:

  LambdaArn:
    Value:
      !GetAtt ToggleAlbLoggingLambda.Arn
