AWSTemplateFormatVersion: 2010-09-09


Description: >
  Deploys 2 instances behind a load balancer running a dockerized kuali research application suite.
  Assumes pre-existence of 2 BU campus private application subnets and 2 BU public gateway subnets.

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: Labelling
        Parameters: 
          - GlobalTag
          - Landscape
      - Label:
          default: Network/Load-balancing
        Parameters:
          - VpcId
          - CampusSubnet1
          - PublicSubnet1
          - CampusSubnet2
          - PublicSubnet2
          - CertificateArn
      - Label: 
          default: "Amazon EC2 Configuration"
        Parameters: 
          - InstanceType
          - BucketName
      - Label: 
          default: "Kuali Services / Docker images"
        Parameters: 
          - CoreImage
          - KcImage
          - PortalImage
          - PdfImage
          - PdfS3BucketName
      - Label: 
          default: "Logging"
        Parameters: 
          - EnableNewRelicAPM
          - EnableNewRelicInfrastructure

Parameters:

  GlobalTag:
    Type: String
    Description: >
      A common value that all resources in this template will have prefixed to
      their name and attached as a tag to establish a bundling through naming convention.
    Default: kuali-ec2-alb

  Landscape:
    Description: Specify which landscape to build for.
    Type: String
    AllowedValues:
    - sb
    - ci
    - qa
    - stg
    - prod
    ConstraintDescription: >
      This parameter is restricted to the following values: sb, ci, qa, stg, prod
    Default: sb

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The id of the vpc to deploy to.
    
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: The first public subnet for the load balancer.

  CampusSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: The first private subnet for one of the ec2 instances.

  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: The second public subnet for the load balancer.

  CampusSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: The second private subnet for one of the ec2 instances.
        
  InstanceType:
    Type: String
    Description: What type of EC2 instance should be used for hosting?
    AllowedValues:
    - t2.large
    - t2.xlarge
    - t3.large
    - t3.xlarge
    - m4.large
    - m4.xlarge
    - m5.large
    - m5.xlarge
    - c5.large
    - c5.xlarge
    ConstraintDescription: Specified instance type is not within selection list.
    Default: m4.large
  
  BucketName:
    Type: String
    Description: The S3 bucket kuali research cloudformation templates, config files, keys, etc. are stored
    Default: kuali-conf

  PdfS3BucketName:
    Type: String
    Description: The name of the s3 bucket the pdf service is to use.

  CoreImage:
    Type: String
    Description: 'Example: 770203350335.dkr.ecr.us-east-1.amazonaws.com/kuali-core:2001.0040'

  KcImage:
    Type: String
    Description: 'Example: 770203350335.dkr.ecr.us-east-1.amazonaws.com/kuali-coeus:2001.0040'

  PortalImage:
    Type: String
    Description: 'Example: 770203350335.dkr.ecr.us-east-1.amazonaws.com/kuali-portal:2001.0040'

  PdfImage:
    Type: String
    Description: 'Example: 770203350335.dkr.ecr.us-east-1.amazonaws.com/kuali-research-pdf:2002.0003'

  CertificateArn:
    Type: String
    Description: The amazon resource name of a certificate that has already been put in ACM

  # NOTE: The type below triggers a check by aws for existence of the keypair as part of a validation check.
  # However, this makes the parameter required, even for stack updates. Use "String" as type to forego the
  # validation check and allow the parameter to be optional during updates.
  EC2KeypairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The keypair for ssh use against the ec2 instance

  EnableNewRelicAPM:
    Type: String
    Description: Is newrelic APM to be enabled for this landscape?
    Default: "false"
    AllowedValues:
    - "true"
    - "false"
    ConstraintDescription: Enter "true" or "false" only.

  EnableNewRelicInfrastructure:
    Type: String
    Description: Is newrelic infrastructure (with logging) to be enabled for this landscape?
    Default: "false"
    AllowedValues:
    - "true"
    - "false"
    ConstraintDescription: Enter "true" or "false" only.
  

Resources:
      
  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ec2_alb/security-group.yaml
      Parameters:
        GlobalTag:
          !Ref GlobalTag
        Landscape:
          !Ref Landscape
        VpcId:
          !Ref VpcId
    
  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ec2_alb/alb.yaml
      Parameters:
        GlobalTag:
          !Ref GlobalTag
        Landscape:
          !Ref Landscape
        VpcId:
          !Ref VpcId
        Subnet1: 
          !Ref PublicSubnet1
        Subnet2: 
          !Ref PublicSubnet2
        SecurityGroups: 
          !GetAtt SecurityGroups.Outputs.ALBSecurityGroups
        CertificateArn:
          !Ref CertificateArn
    
  Instance1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ec2_alb/ec2.yaml
      Parameters:
        GlobalTag:
          !Ref GlobalTag
        Landscape:
          !Ref Landscape
        SecurityGroupsId:
          !GetAtt SecurityGroups.Outputs.EC2SecurityGroupsId
        LoadBalancerUrl:
          !GetAtt ALB.Outputs.LoadBalancerUrl
        InstanceType:
          !Ref InstanceType
        CampusSubnet:
          !Ref CampusSubnet1
        BucketName:
          !Ref BucketName
        PdfS3BucketName:
          !Ref PdfS3BucketName
        CoreImage:
          !Ref CoreImage
        KcImage:
          !Ref KcImage
        PortalImage:
          !Ref PortalImage
        PdfImage:
          !Ref PdfImage
        EC2KeypairName:
          !Ref EC2KeypairName
        EnableNewRelicAPM:
          !Ref EnableNewRelicAPM
        EnableNewRelicInfrastructure:
          !Ref EnableNewRelicInfrastructure

  Instance2:
    Type: AWS::CloudFormation::Stack
    DependsOn: Instance1
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ec2_alb/ec2.yaml
      Parameters:
        GlobalTag:
          !Ref GlobalTag
        Landscape:
          !Ref Landscape
        SecurityGroupsId:
          !GetAtt SecurityGroups.Outputs.EC2SecurityGroupsId
        LoadBalancerUrl:
          !GetAtt ALB.Outputs.LoadBalancerUrl
        CampusSubnet:
          !Ref CampusSubnet2
        InstanceType:
          !Ref InstanceType
        BucketName:
          !Ref BucketName
        PdfS3BucketName: 
          !Ref PdfS3BucketName
        CoreImage:
          !Ref CoreImage
        KcImage:
          !Ref KcImage
        PortalImage:
          !Ref PortalImage
        PdfImage:
          !Ref PdfImage
        EC2KeypairName:
          !Ref EC2KeypairName
        EnableNewRelicAPM:
          !Ref EnableNewRelicAPM
        EnableNewRelicInfrastructure:
          !Ref EnableNewRelicInfrastructure
        InstanceProfile:
          !GetAtt Instance1.Outputs.EC2InstanceProfile
        InstanceRole:
          !GetAtt Instance1.Outputs.EC2Role
        EC2InstanceLogsGroupArn:
          !GetAtt Instance1.Outputs.EC2InstanceLogsGroupArn
            
  Services:
    Type: AWS::CloudFormation::Stack
    DependsOn: Instance2
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ec2_alb/services.yaml
      Parameters:
        GlobalTag:
          !Ref GlobalTag
        Landscape:
          !Ref Landscape
        VpcId:
          !Ref VpcId
        Listener:
          !GetAtt ALB.Outputs.Listener
        InstanceId1:
          !GetAtt Instance1.Outputs.InstanceId
        InstanceId2:
          !GetAtt Instance2.Outputs.InstanceId
        PdfS3BucketName: 
          !Ref PdfS3BucketName


Outputs:

  LoadBalancerUrl:
    Description: This will be the url that the app is publicly addressable on
    Value: !GetAtt ALB.Outputs.LoadBalancerUrl
    