AWSTemplateFormatVersion: 2010-09-09

Description: >
  Deploys 2 instances behind a load balancer running a dockerized kuali research application suite.
  Assumes that the subnets must also be created.

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: Labelling
        Parameters: 
          - GlobalTag
          - Landscape
      - Label:
          default: Network/Load-balancing
        Parameters:
          - VpcId
          - InternetGatewayId
          - AvailabilityZone1
          - AvailabilityZone2
          - CertificateArn
      - Label: 
          default: "Amazon EC2 Configuration"
        Parameters: 
          - InstanceType
          - BucketName
      - Label: 
          default: "Kuali Services / Docker images"
        Parameters: 
          - CoreImage
          - KcImage
          - PortalImage
          - PdfImage
      - Label: 
          default: "Logging"
        Parameters: 
          - EnableNewRelicAPM
          - EnableNewRelicInfrastructure


Parameters:

  GlobalTag:
    Type: String
    Description: >
      A common value that all resources in this template will have prefixed to
      their name and attached as a tag to establish a bundling through naming convention.
    Default: kuali-ec2-alb

  Landscape:
    Description: Specify which landscape to build for.
    Type: String
    AllowedValues:
    - sb
    - ci
    - qa
    - stg
    - prod
    ConstraintDescription: >
      This parameter is restricted to the following values: sb, ci, qa, stg, prod
    Default: sb

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The id of the vpc to deploy to.

  InternetGatewayId:
    Type: String
    Description: The id of the internet gateway for the vpc.
  
  AvailabilityZone1:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: The availability zone for the first ec2 instance and subnet set.
    Default: us-east-1a
  
  AvailabilityZone2:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: The availability zone for the second ec2 instance and subnet set.
    Default: us-east-1b
          
  InstanceType:
    Type: String
    Description: What type of EC2 instance should be used for hosting?
    AllowedValues:
    - t2.large
    - t2.xlarge
    - t3.large
    - t3.xlarge
    - m4.large
    - m4.xlarge
    - m5.large
    - m5.xlarge
    - c5.large
    - c5.xlarge
    ConstraintDescription: Specified instance type is not within selection list.
    Default: m4.large
  
  BucketName:
    Type: String
    Description: The S3 bucket kuali research cloudformation templates, config files, keys, etc. are stored
    Default: kuali-research-ec2-setup

  CoreImage:
    Type: String
    Description: 'Example: 730096353738.dkr.ecr.us-east-1.amazonaws.com/core:2001.0040'

  KcImage:
    Type: String
    Description: 'Example: 730096353738.dkr.ecr.us-east-1.amazonaws.com/coeus:2001.0040'

  PortalImage:
    Type: String
    Description: 'Example: 730096353738.dkr.ecr.us-east-1.amazonaws.com/portal:2001.0040'

  PdfImage:
    Type: String
    Description: 'Example: 730096353738.dkr.ecr.us-east-1.amazonaws.com/research-pdf:2002.0003'

  CertificateArn:
    Type: String
    Description: The amazon resource name of a certificate that has already been put in ACM

  EnableNewRelicAPM:
    Type: String
    Description: Is newrelic APM to be enabled for this landscape?
    Default: "false"
    AllowedValues:
    - "true"
    - "false"
    ConstraintDescription: Enter "true" or "false" only.
    Default: "false"

  EnableNewRelicInfrastructure:
    Type: String
    Description: Is newrelic infrastructure (with logging) to be enabled for this landscape?
    Default: "false"
    AllowedValues:
    - "true"
    - "false"
    ConstraintDescription: Enter "true" or "false" only.
    Default: "false"
    
Resources:
    
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Description: >
      First of 2 public subnets in which is deployed a NAT gateway for handling 
      traffic that is outbound to the internet.
    Properties:
      AvailabilityZone: !Ref AvailabilityZone1
      CidrBlock: 172.31.96.0/25
      MapPublicIpOnLaunch: true
      VpcId:
        !Ref VpcId
      Tags:
      - Key: Name
        Value:
         !Sub "${GlobalTag}-${Landscape}-public-subnet1"

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Description: >
      The first of 2 private subnets to which are routed traffic inbound from the internet 
      through the application load balancer.
    Properties:
      AvailabilityZone: !Ref AvailabilityZone1
      CidrBlock: 172.31.96.128/25
      MapPublicIpOnLaunch: false
      VpcId:
        !Ref VpcId
      Tags:
      - Key: Name
        Value:
          !Sub "${GlobalTag}-${Landscape}-private-subnet1"

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Description: >
      The second of 2 public subnets in which is deployed a NAT gateway
      for handling traffic that is outbound to the internet
    Properties:
      AvailabilityZone: !Ref AvailabilityZone2
      CidrBlock: 172.31.97.0/25
      MapPublicIpOnLaunch: true
      VpcId:
        !Ref VpcId
      Tags:
      - Key: Name
        Value:
          !Sub "${GlobalTag}-${Landscape}-public-subnet2"

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Description: >
      The second of 2 private subnets to which are routed traffic inbound from the internet 
      through the application load balancer.
    Properties:
      AvailabilityZone: !Ref AvailabilityZone2
      CidrBlock: 172.31.97.128/25
      MapPublicIpOnLaunch: false
      VpcId:
        !Ref VpcId
      Tags:
      - Key: Name
        Value:
          !Sub "${GlobalTag}-${Landscape}-private-subnet2"

  Main:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ec2_alb/main-existing-subnets.yaml
      Parameters:
        GlobalTag:
          !Ref GlobalTag
        Landscape:
          !Ref Landscape
        VpcId:
          !Ref VpcId
        InternetGatewayId:
          !Ref InternetGatewayId
        InstanceType:
          !Ref InstanceType
        BucketName:
          !Ref BucketName
        CoreImage:
          !Ref CoreImage
        KcImage:
          !Ref KcImage
        PortalImage:
          !Ref PortalImage
        PdfImage:
          !Ref PdfImage
        PublicSubnet1:
          !Ref PublicSubnet1
        PrivateSubnet1:
          !Ref PrivateSubnet1
        PublicSubnet2:
          !Ref PublicSubnet2
        PrivateSubnet2:
          !Ref PrivateSubnet2
        CertificateArn:
          !Ref CertificateArn
        EnableNewRelicAPM:
          !Ref EnableNewRelicAPM
        EnableNewRelicInfrastructure:
          !Ref EnableNewRelicInfrastructure

Outputs:

  LoadBalancerUrl:
    Description: This will be the url that the app is publicly addressable on
    Value: !GetAtt Main.Outputs.LoadBalancerUrl