Description: Establishes an ALB and an EC2 security group.

Parameters:

  GlobalTag:
    Type: String
    Description: >
      A common value that all resources in this template will have prefixed to
      their name and attached as a tag to establish a bundling through naming convention. If a nested stack,
      this will most likely be the name of the top-most stack.
    Default: kuali-ec2-alb

  Landscape:
    Description: Specify which landscape to build for.
    Type: String
    AllowedValues:
    - sb
    - ci
    - qa
    - stg
    - prod
    ConstraintDescription: >
      This parameter is restricted to the following values: sb, ci, qa, stg, prod
    Default: sb

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The id of the vpc to deploy to.
    

Resources:

  # This security group defines who/where is allowed to access the ECS hosts directly.
  # By default we're just allowing access from the load balancer.  If you want to SSH
  # into the hosts, or expose non-load balanced services you can open their ports here.
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: ALBSecurityGroup
    Properties:
      VpcId:
        !Ref VpcId
      GroupName:
        !Sub ${GlobalTag}-${Landscape}-ec2-security-group
      GroupDescription:
        !Join
        - " "
        - - Defines who/where is allowed to access the EC2 Host directly.
          - 'This includes allowing access from: '
          - 1) The application load balancer
          - 2) SSH access into the ec2 hosts
      Tags:
      - Key: Name
        Value: 
          !Sub ${GlobalTag}-${Landscape}-ec2-security-group
      SecurityGroupIngress:
      - IpProtocol: -1
        SourceSecurityGroupId:
          !Ref ALBSecurityGroup
        Description: Allows inbound access to the EC2 instance from the ALB only.
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
        Description: Allows SSH access to ECS host instances directly without requiring it originate from the ALB.

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        !Ref VpcId
      GroupName:
        !Sub ${GlobalTag}-${Landscape}-alb-sg
      GroupDescription:
        This security group defines who/where is allowed to access the application
        load balancer that sits in front of the private subnets. Currently open to the public 
        internet (0.0.0.0/0) but can be restricted to certain ports.
      Tags:
      - Key: Name
        Value: 
          !Sub ${GlobalTag}-${Landscape}-alb-sg
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        IpProtocol: -1
        Description: Allow for the ALB to send over any port by opening them all up to it.
        # This does not effectively open all ports up - the ALB itself is only configured to route over a handful of them.


Outputs:
  EC2SecurityGroupId:
    Description: A reference to the security group for the EC2 instance
    Value:
      # Need the Id, not the ARN, so passing the groupId attribute (ie: sg-94b3a1f6)
      !GetAtt  EC2SecurityGroup.GroupId
  ALBSecurityGroup:
    Description: A reference to the security group for load balancer
    Value:
      !Ref ALBSecurityGroup
