AWSTemplateFormatVersion: '2010-09-09'

Description: |
  RDS instance for kuali oracle database. Includes KCOEUS, KULUSERMAINT, SAPBWKCRM, SAPETLKCRM, SNAPLOGIC, and KCRMPROC schemas

Parameters:

  GlobalTag:
    Type: String
    Description: >
      A common value that all resources in this template will have prefixed to
      their name and attached as a tag to establish a bundling through naming convention.
    Default: kuali-oracle

  Landscape:
    Description: Specify a name for your landscape
    Type: String
    AllowedPattern: "[a-zA-Z\\d]{1,12}"
    ConstraintDescription: Up to 12 letters and/or numbers

  Baseline:
    Description: Specify one of a set of standard landscapes. Indicates secrets manager secrets to use for database access.
    Type: String
    AllowedPattern: "[a-zA-Z\\d]{1,12}"
    ConstraintDescription: Up to 12 letters and/or numbers
    
  Service:
    Description: Service catalog name
    Type: String
    Default: research-administration

  Function:
    Description: The Function within the Service
    Type: String
    Default: kuali

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The id of the vpc to deploy to.
  
  TemplateBucketName:
    Type: String
    Description: The S3 bucket kuali research cloudformation templates, config files, keys, etc. are stored
    Default: kuali-conf

  DBInstanceClass:
    Description: |
      The compute and memory capacity of the DB instance. 
      Not all DB instance classes are available in all AWS Regions, or for all database engines.
    Default: db.m5.large 
    Type: String
    AllowedValues:
    - db.m5.large
    - db.m5.xlarge
    - db.m5.2xlarge
    - db.m5.4xlarge
    - db.r5.large
    - db.r5.xlarge
    - db.r5.2xlarge
    - db.r5.4xlarge

  JumpboxInstanceType:
    Type: String
    Description: What type of EC2 instance should be used for hosting the jumpbox?
    AllowedValues:
    - t2.small
    - t2.medium
    - t2.large
    - t3.small
    - t3.medium
    - t3.large
    - none
    ConstraintDescription: Specified instance type is not within selection list.
    Default: t3.small

  DBSnapshotARN:
    Type: String
    Description: By specifying this property, you can create a DB instance from the specified DB snapshot identified by its ARN
    Default: none

  MultiAZ:
    Type: String
    Description: |
      Specifies whether the database instance is a multiple Availability Zone deployment. 
      Set to false to reduce costs by having only one rds instance (deployed to the AZ of the first DB subnet). 
      Otherwise, database storage is replicated across all the Availability Zones spanned by the database subnet group.
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'false'

  AvailabilityZone:
    # Type: AWS::EC2::AvailabilityZone::Name
    Type: String
    Description: >
      This parameter is provided if multi-az is false. While it is not required in a single-az deployment, it provides a way
      to ensure which of the two subnets in the database subnet group the rds instance gets deployed two. Unfortunately, a
      database subnet group must have two or more subnets, spanning at least two availability zones must be specified, even 
      for deployments where multi-az is false (AWS says it's for in case you change you mind and want to convert to multi-az).
    Default: 'N/A, MultiAZ'

  Engine:
    Type: String
    Description: The name of the database engine that you want to use for this DB instance
    Default: oracle-se2
    AllowedValues:
    - oracle-ee
    - oracle-se2
    - oracle-se1
    - oracle-se

  # Pick the latest version for a family as follows:
  #   aws rds describe-db-engine-versions \
  #     --engine oracle-ee \
  #     --output text \
  #     --query 'DBEngineVersions[?DBParameterGroupFamily==`oracle-ee-19`].{EngineVersion:EngineVersion}' | tail -n -1
  # Familys:
  #   [engine]-19, [engine]-18, [engine]-12.2, [engine]-12.1, [engine]-11.2
  EngineVersion:
    Type: String
    Description: The version number of the database engine to use.
    # Default: 19.0.0.0.ru-2020-04.rur-2020-04.r1

  DBName:
    Type: String
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Must begin with a letter and contain a minimum of 4 alphanumeric characters.
    Default: Kuali
    Description: |
      The Oracle System ID (SID) of the created DB instance. 
      If you specify null, the default value ORCL is used. 
      You can't specify the string NULL, or any other reserved word, for DBName
    MaxLength: 64
    MinLength: 4

  Port:
    Description: TCP/IP Port for the Database Instance
    Type: Number
    Default: 1521
    ConstraintDescription: Must be in the range [1115-65535]
    MinValue: 1115
    MaxValue: 65535
  
  LicenseModel:
    Type: String
    Default: license-included
    AllowedValues:
    - license-included
    - bring-your-own-license
    - general-public-license

  # https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html
  AllocatedStorage:
    Type: Number
    Description: The amount of storage (in gigabytes) to be initially allocated for the database instance
    ConstraintDescription: Must be in the range [1-1000]
    MinValue: 1
    MaxValue: 1000
    Default: 500

  AutoMinorVersionUpgrade:
    Description: |
      A value that indicates whether minor engine upgrades are applied automatically to the DB instance during the maintenance window. 
      If true, minor engine upgrades are applied automatically.
    Type: String
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'true'

  BackupRetentionPeriod:
    Type: Number
    Description: |
      The number of days for which automated backups are retained. 
      Setting this parameter to a positive number enables backups. 
      Setting this parameter to 0 disables automated backups.
    ConstraintDescription: Must be in the range [1-30]
    MinValue: 1
    MaxValue: 30
    Default: 10
  
  CharacterSetName:
    Type: String
    Description: For supported engines, indicates that the DB instance should be associated with the specified character set.
    Default: WE8MSWIN1252

  Iops:
    Type: Number
    Description: |
      The number of I/O operations per second (IOPS) that the database provisions. 
      Omit this parameter and storage type will be gps where iops are burstable, 
      cheaper, but potentially less peformant if the database has read/write intensive use)
    ConstraintDescription: Must be in range [1000-10000]
    MinValue: 0
    MaxValue: 10000
    Default: 0    

  DBSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Id of the first private subnet of the RDS subnet group

  DBSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Id of the second private subnet of the RDS subnet group

  DBSubnetCIDR1:
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: It must be a valid IP CIDR range of the form x.x.x.x/x. 
    Description: |
      The IP address range of the subnet containing the oracle RDS instances. 
      Accessible from the campus subnet over the default "local" route.
    MaxLength: 18
    MinLength: 9 
    Type: String

  DBSubnetCIDR2:
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: It must be a valid IP CIDR range of the form x.x.x.x/x. 
    Description: |
      The IP address range of the subnet containing the oracle RDS instances. 
      Accessible from the campus subnet over the default "local" route.
    MaxLength: 18
    MinLength: 9 
    Type: String

  CampusSubnetCIDR1:
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: It must be a valid IP CIDR range of the form x.x.x.x/x. 
    Description: |
      The IP address range that can be used to connect to the RDS instances from your local machine.
      Your local machine will have aqcuired an IP address from the BU VPN by logging on, which in turn goes through the 
      campus subnet via the transit gateway. Therefore it should be a campus subnet IP allowed for ingress.
    MaxLength: 18
    MinLength: 9 
    Type: String

  CampusSubnetCIDR2:
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: It must be a valid IP CIDR range of the form x.x.x.x/x. 
    Description: |
      The IP address range that can be used to connect to the RDS instances from your local machine.
      Your local machine will have aqcuired an IP address from the BU VPN by logging on, which in turn goes through the 
      campus subnet via the transit gateway. Therefore it should be a campus subnet IP allowed for ingress.
    MaxLength: 18
    MinLength: 9 
    Type: String

  LogGroupRetention:
    Type: Number
    Description: How old in days can the rds log groups content get before it is deleted?
    AllowedValues: [0, 1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
    ConstraintDescription: Allowed values - 1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, and 3653
    Default: 0


Conditions:
  SingleDBAvailabilityZone: !Equals [!Ref MultiAZ, 'false']
  CreateFromSnapshot: !Not [!Equals [!Ref DBSnapshotARN, none]]
  IsProd: !Equals [!Ref Landscape, prod]
  IopsSpecified: !Not [!Equals [!Ref Iops, 0]]
  CreateJumpboxInstance: !Not [!Equals [!Ref JumpboxInstanceType, none]]
  MonoCampusSubnet: !Equals [!Ref CampusSubnetCIDR1, !Ref CampusSubnetCIDR2]
  LogGroupRetentionSpecified: !Not [!Equals [!Ref LogGroupRetention, 0]]

Resources:

  # MasterUserPassword:
  #   Type: AWS::SecretsManager::Secret
  #   Properties: 
  #     Name: !Sub kuali/${Landscape}/kuali-oracle-rds-admin-password
  #     Description: !Sub The oracle master user password for the kuali research rds ${Landscape} database
  #     GenerateSecretString: 
  #       ExcludeCharacters: '"@/\|'
  #       # ExcludePunctuation: false ! " # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~
  #       PasswordLength: 15
  #       SecretStringTemplate: '{"MasterUsername": "admin"}'
  #       GenerateStringKey: "MasterUserPassword"
  #     # KmsKeyId: String
  #     # SecretString: String
  #     Tags: 
  #     - Key: Name
  #       Value: !Sub kuali/${Landscape}/kuali-oracle-rds-admin-password

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet available for the Oracle Instance
      SubnetIds:
        - !Ref DBSubnet1
        - !Ref DBSubnet2

  DBVpcSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Security group for migration instances.
      SecurityGroupIngress:
      # - CidrIp: 0.0.0.0/0
      #   FromPort: 0
      #   IpProtocol: -1
      #   ToPort: 65535
      - CidrIp: !Ref CampusSubnetCIDR1
        FromPort: !Ref Port
        IpProtocol: tcp
        ToPort: !Ref Port
      - !If
        - MonoCampusSubnet
        - !Ref AWS::NoValue
        - CidrIp: !Ref CampusSubnetCIDR2
          FromPort: !Ref Port
          IpProtocol: tcp
          ToPort: !Ref Port
      - CidrIp: !Ref DBSubnetCIDR1
        FromPort: !Ref Port
        IpProtocol: tcp
        ToPort: !Ref Port
      - CidrIp: !Ref DBSubnetCIDR2
        FromPort: !Ref Port
        IpProtocol: tcp
        ToPort: !Ref Port

  # Anticipate the name of, and create the log groups that the rds instances "EnableCloudwatchLogsExports"
  # setting is configured to automatically create so that cloudformation has control of the retention settings
  # and deletion policy. Included are "DependsOn" settings that ensure that these log groups get created BEFORE
  # the rds instance so that there is no race condition during stack creation. This should be enough to ensure
  # that these log groups are removed when the stack is deleted and are not orphaned.
  TraceLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties: 
      LogGroupName: !Sub /aws/rds/instance/${GlobalTag}-${Landscape}/trace
      RetentionInDays: 
        !If 
        - LogGroupRetentionSpecified
        - !Ref LogGroupRetention
        - !If [ IsProd, 365, 30 ]
  AuditLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: TraceLogGroup
    DeletionPolicy: Delete
    Properties: 
      LogGroupName: !Sub /aws/rds/instance/${GlobalTag}-${Landscape}/audit
      RetentionInDays: 
        !If 
        - LogGroupRetentionSpecified
        - !Ref LogGroupRetention
        - !If [ IsProd, 365, 30 ]
  AlertLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: AuditLogGroup
    DeletionPolicy: Delete
    Properties: 
      LogGroupName: !Sub /aws/rds/instance/${GlobalTag}-${Landscape}/alert
      RetentionInDays: 
        !If 
        - LogGroupRetentionSpecified
        - !Ref LogGroupRetention
        - !If [ IsProd, 365, 30 ]
  ListenerLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: AlertLogGroup
    DeletionPolicy: Delete
    Properties: 
      LogGroupName: !Sub /aws/rds/instance/${GlobalTag}-${Landscape}/listener
      RetentionInDays: 
        !If 
        - LogGroupRetentionSpecified
        - !Ref LogGroupRetention
        - !If [ IsProd, 365, 30 ]

  DBInstance:
    Type: AWS::RDS::DBInstance
    # DependsOn: MasterUserPassword
    DependsOn: ListenerLogGroup
    Properties:
      AllocatedStorage: !Ref AllocatedStorage 
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
      AvailabilityZone: 
        !If 
        - SingleDBAvailabilityZone
        - !Ref AvailabilityZone
        - !Ref AWS::NoValue
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      CharacterSetName: !Ref CharacterSetName
      CopyTagsToSnapshot: true
      DBInstanceClass: !Ref DBInstanceClass
      DBInstanceIdentifier: !Sub ${GlobalTag}-${Landscape}
      DBName: !Ref DBName
      DBSnapshotIdentifier: 
        !If
        - CreateFromSnapshot
        - !Ref DBSnapshotARN
        - !Ref AWS::NoValue
      DBSubnetGroupName: !Ref DBSubnetGroup
      DeletionProtection:
        !If
        - IsProd
        - true
        - !Ref AWS::NoValue
      DeleteAutomatedBackups:
        !If
        - IsProd
        - false
        - true
      EnableCloudwatchLogsExports:
        - trace
        - audit
        - alert
        - listener
      EnablePerformanceInsights:
        !If 
        - IsProd
        - true
        - !Ref AWS::NoValue
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      Iops:
        !If
        - IopsSpecified
        - !Ref Iops
        - !Ref AWS::NoValue # Storage type defaults to gp2
      LicenseModel: !Ref LicenseModel
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html
      MasterUsername: !Sub '{{resolve:secretsmanager:kuali/${Baseline}/kuali-oracle-rds-admin-password:SecretString:MasterUsername}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:kuali/${Baseline}/kuali-oracle-rds-admin-password:SecretString:MasterUserPassword}}'
      MultiAZ: !Ref MultiAZ # If true, it should create a second standby rds instance in the second subnet of the subnet group.
      PerformanceInsightsRetentionPeriod: 
        !If 
        - IsProd
        - 30
        - !Ref AWS::NoValue
      Port: !Ref Port
      # https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithAutomatedBackups.html#USER_WorkingWithAutomatedBackups.BackupWindow
      PreferredBackupWindow: 22:00-23:00
      PreferredMaintenanceWindow: sat:20:00-sat:21:00
      PubliclyAccessible: 'false'
      StorageType:
        !If
        - IopsSpecified
        - !Ref AWS::NoValue # Storage type defaults to io1
        - gp2
      Tags:
      - Key: Name
        Value: !Sub ${GlobalTag}-${Landscape}
      - Key: App
        Value: Kuali
      - Key: Landscape
        Value: !Ref Landscape
      - Key: Baseline
        Value: !Ref Baseline
      - Key: Version
        Value: 1
      - Key: Service
        Value: !Ref Service
      - Key: Function
        Value: !Ref Function
      VPCSecurityGroups:
      - !Ref DBVpcSecurityGroup


  DBJumpbox:
    Type: AWS::CloudFormation::Stack
    Condition: CreateJumpboxInstance
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${TemplateBucketName}/cloudformation/kuali_rds/jumpbox/jumpbox.yaml
      Parameters:
        Landscape: !Ref Landscape
        TemplateBucketName: !Ref TemplateBucketName
        JumpboxInstanceType: !Ref JumpboxInstanceType
        VpcId: !Ref VpcId
        DBSubnet1: !Ref DBSubnet1
        DBSubnetCIDR1: !Ref DBSubnetCIDR1
        DBSubnetCIDR2: !Ref DBSubnetCIDR2
        DBPort: !Ref Port


Outputs:

  OracleJDBCConnectionString:
    Description: JDBC connection string for Oracle database
    Value: !Join 
      - ""
      - - jdbc:oracle:thin:@
        - !GetAtt 
          - DBInstance
          - Endpoint.Address
        - ":"
        - !GetAtt 
          - DBInstance
          - Endpoint.Port
        - ":"
        - !Ref DBName
