Description: >
  This is the primary template for building a cloud formation stack for
  the Kuali Research ecs cluster. All parameters for nested templates are set here.

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: Labelling
        Parameters: 
          - GlobalTag
          - Landscape
      - Label:
          default: Network/Load-balancing
        Parameters:
          - VpcId
          - CampusSubnet1
          - PublicSubnet1
          - CampusSubnet2
          - PublicSubnet2
          - CertificateArn
          - EnableWAF
          - HostedZoneName
      - Label: 
          default: "Amazon EC2 Configuration"
        Parameters: 
          - InstanceType
          - BucketName
      - Label: 
          default: "Kuali Services / Docker images"
        Parameters: 
          - CoreImage
          - KcImage
          - PortalImage
          - PdfImage
          - PdfS3BucketName
      - Label: 
          default: "Logging"
        Parameters: 
          - EnableALBLogging
          - EnableNewRelicAPM
          - EnableNewRelicInfrastructure

Parameters:

  GlobalTag:
    Type: String
    Description: >
      A common value that all resources in this template will have prefixed to
      their name and attached as a tag to establish a bundling through naming convention.
    Default: kuali-ecs

  Landscape:
    Description: Specify which landscape to build for.
    Type: String
    AllowedValues:
    - sb
    - ci
    - qa
    - stg
    - prod
    ConstraintDescription: >
      This parameter is restricted to the following values: sb, ci, qa, stg, prod
    Default: sb

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The id of the vpc to deploy to.
    
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: The first public subnet for the load balancer.

  CampusSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: The first private subnet for one of the ec2 instances.

  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: The second public subnet for the load balancer.

  CampusSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: The second private subnet for one of the ec2 instances.
        
  InstanceType:
    Type: String
    Description: What type of EC2 instance should be used for hosting?
    AllowedValues:
    - t2.large
    - t2.xlarge
    - t3.large
    - t3.xlarge
    - m4.large
    - m4.xlarge
    - m5.large
    - m5.xlarge
    - c5.large
    - c5.xlarge
    ConstraintDescription: Specified instance type is not within selection list.
    Default: m4.large
  
  BucketName:
    Type: String
    Description: The S3 bucket kuali research cloudformation templates, config files, keys, etc. are stored
    Default: kuali-conf

  PdfS3BucketName:
    Type: String
    Description: The name of the s3 bucket the pdf service is to use.

  MinClusterSize:
    Type: Number
    Description: How many EC2 instances are to be initially deployed as ECS hosts
      accross your cluster?
    AllowedValues: [ 2, 3, 4 ]
    ConstraintDescription: Minimum cluster size is limited between 2 and 4 instances.
    Default: 2

  MaxClusterSize:
    Type: Number
    Description: How many EC2 instances are to be initially deployed as ECS hosts
      accross your cluster?
    AllowedValues: [ 2, 3, 4, 5, 6 ]
    ConstraintDescription: Maximum cluster size is limited between 1 and 6 instances.
    Default: 3

  CoreImage:
    Type: String
    Description: 'Example: 770203350335.dkr.ecr.us-east-1.amazonaws.com/kuali-core:2001.0040'

  KcImage:
    Type: String
    Description: 'Example: 770203350335.dkr.ecr.us-east-1.amazonaws.com/kuali-coeus:2001.0040'

  PortalImage:
    Type: String
    Description: 'Example: 770203350335.dkr.ecr.us-east-1.amazonaws.com/kuali-portal:2001.0040'

  PdfImage:
    Type: String
    Description: 'Example: 770203350335.dkr.ecr.us-east-1.amazonaws.com/kuali-research-pdf:2002.0003'

  CertificateArn:
    Type: String
    Description: The amazon resource name of a certificate that has already been put in ACM

  EC2KeypairName:
    # Type: AWS::EC2::KeyPair::KeyName
    Type: String
    Description: The keypair for ssh use against the ec2 instance
    Default: empty

  EnableNewRelicAPM:
    Type: String
    Description: Is newrelic APM to be enabled for this landscape?
    Default: "false"
    AllowedValues:
    - "true"
    - "false"
    ConstraintDescription: Enter "true" or "false" only.

  EnableNewRelicInfrastructure:
    Type: String
    Description: Is newrelic infrastructure (with logging) to be enabled for this landscape?
    Default: "false"
    AllowedValues:
    - "true"
    - "false"
    ConstraintDescription: Enter "true" or "false" only.

  EnableWAF:
    Type: String
    Description: Does the ALB traffic need to go through a WAF?
    Default: "true"
    AllowedValues:
    - "true"
    - "false"

  EnableALBLogging:
    Type: String
    Description: Does the ALB traffic need to be logged? (If WAF is enabled, the value you set here will be overriden to true)
    Default: "false"
    AllowedValues:
    - "true"
    - "false"

  MongoSubnetId:
    Type: String
    Description: Id of the private application subnet where a new mongo database ec2 instance is optionally created.
    Default: empty

  HostedZoneName:
    Type: String
    Description: If included, a DNS record will be created and registered with the specified HostedZone
    Default: empty


Conditions:
  CreateWAF: !Equals [!Ref EnableWAF, 'true']
  CreateDnsRecord: !Not [!Equals [!Ref HostedZoneName, empty]]
  CreateMongoEc2Instance: !Not [!Equals [!Ref MongoSubnetId, empty]]
  CreateAlbLogsBuckets: !Or [!Equals [!Ref EnableALBLogging, 'true' ], Condition: CreateWAF]
  UseKeypair: !Not [!Equals [!Ref EC2KeypairName, empty]]


Resources:

  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ecs/security-group.yaml
      Parameters:
        GlobalTag:
          !Ref GlobalTag
        Landscape:
          !Ref Landscape
        VpcId: 
          !Ref VpcId

  ALBWAFLogs:
    Type: AWS::CloudFormation::Stack
    Condition: CreateAlbLogsBuckets
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_alb/logs.yaml
      Parameters:
        GlobalTag:
          !Ref GlobalTag
        Landscape:
          !Ref Landscape
        BucketName: !Ref BucketName

  WAF:
    Type: AWS::CloudFormation::Stack
    Condition: CreateWAF
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_waf/waf.yaml
      Parameters:
        GlobalTag:
          !Ref GlobalTag
        Landscape:
          !Ref Landscape
        AlbLogsBucketName:
          !If
            - CreateAlbLogsBuckets
            - !GetAtt ALBWAFLogs.Outputs.ALBLogBucketName
            - !Ref AWS::NoValue
        GlueAccessLogsDatabaseName:
          !If
            - CreateAlbLogsBuckets
            - !GetAtt ALBWAFLogs.Outputs.GlueAccessLogsDatabaseName
            - !Ref AWS::NoValue
        BucketName: !Ref BucketName

  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_alb/alb.yaml
      Parameters:
        GlobalTag:
          !Ref GlobalTag
        Landscape:
          !Ref Landscape
        VpcId: 
          !Ref VpcId
        Subnet1: 
          !Ref PublicSubnet1
        Subnet2: 
          !Ref PublicSubnet2
        SecurityGroup: 
          !GetAtt SecurityGroups.Outputs.ALBSecurityGroup
        CertificateArn:
          !Ref CertificateArn
        WafWebAclArn:
          !If
            - CreateWAF
            - !GetAtt WAF.Outputs.WafWebAclArn
            - !Ref AWS::NoValue
        HostedZoneName:
          !If
            - CreateDnsRecord
            - !Ref HostedZoneName
            - !Ref AWS::NoValue
        AlbLogsBucketName:
          !If
            - CreateAlbLogsBuckets
            - !GetAtt ALBWAFLogs.Outputs.ALBLogBucketName
            - !Ref AWS::NoValue

  MongoDbInstance:
    Type: AWS::CloudFormation::Stack
    Condition: CreateMongoEc2Instance
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_mongo/mongo.yaml
      Parameters:
        GlobalTag:
          !Sub ${GlobalTag}-mongo
        Landscape:
          !Ref Landscape
        VpcId:
          !Ref VpcId
        ApplicationSecurityGroupId:
          !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
        MongoSubnet:
          !Ref MongoSubnetId
        BucketName: !Ref BucketName

  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ecs/cluster.yaml
      Parameters:
        GlobalTag:
          !Ref GlobalTag
        Landscape:
          !Ref Landscape
        SecurityGroupId:
          !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
        VpcId: 
          !Ref VpcId
        DNSName:
          !If 
            - CreateDnsRecord
            - !Ref HostedZoneName
            - !GetAtt ALB.Outputs.DNSName
        UsingRoute53: !If [ CreateDnsRecord, 'true', 'false' ]
        InstanceType:
          !Ref InstanceType
        CampusSubnet1:
          !Ref CampusSubnet1
        CampusSubnet2:
          !Ref CampusSubnet2
        MongoEc2Ip:
          !If
            - CreateMongoEc2Instance
            - !GetAtt MongoDbInstance.Outputs.PrivateIP
            - !Ref AWS::NoValue
        MinClusterSize:
          !Ref MinClusterSize
        MaxClusterSize:
          !Ref MaxClusterSize
        BucketName:
          !Ref BucketName
        PdfS3BucketName: 
          !Ref PdfS3BucketName
        EC2KeypairName:
          !If 
            - UseKeypair
            - !Ref EC2KeypairName
            - !Ref AWS::NoValue
        EnableNewRelicAPM:
          !Ref EnableNewRelicAPM
        EnableNewRelicInfrastructure:
          !Ref EnableNewRelicInfrastructure

  KualiCoreService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ecs/service-core.yaml
      Parameters:
        GlobalTag:
          !Ref GlobalTag
        Landscape:
          !Ref Landscape
        VpcId:
          !Ref VpcId
        ClusterId:
          !GetAtt ECS.Outputs.Cluster
        DesiredCount: !Ref MinClusterSize
        MaxCount: !Ref MaxClusterSize
        Listener:
          !GetAtt ALB.Outputs.Listener
        ECSContainerInstanceAutoScalingRoleARN:
          !GetAtt ECS.Outputs.ECSContainerInstanceAutoScalingRoleARN
        CoreImage:
          !Ref CoreImage

  KualiPdfService:
    Type: AWS::CloudFormation::Stack
    DependsOn: KualiCoreService
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ecs/service-pdf.yaml
      Parameters:
        GlobalTag:
          !Ref GlobalTag
        Landscape:
          !Ref Landscape
        VpcId:
          !Ref VpcId
        ClusterId:
          !GetAtt ECS.Outputs.Cluster
        DesiredCount: !Ref MinClusterSize
        MaxCount: !Ref MaxClusterSize
        Listener:
          !GetAtt ALB.Outputs.Listener
        ECSContainerInstanceAutoScalingRoleARN:
          !GetAtt ECS.Outputs.ECSContainerInstanceAutoScalingRoleARN
        PdfImage:
          !Ref PdfImage
        PdfS3BucketName: 
          !Ref PdfS3BucketName

  KualiDashboardService:
    Type: AWS::CloudFormation::Stack
    DependsOn: KualiPdfService
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ecs/service-dashboard.yaml
      Parameters:
        GlobalTag:
          !Ref GlobalTag
        Landscape:
          !Ref Landscape
        VpcId:
          !Ref VpcId
        ClusterId:
          !GetAtt ECS.Outputs.Cluster
        DesiredCount: !Ref MinClusterSize
        MaxCount: !Ref MaxClusterSize
        Listener:
          !GetAtt ALB.Outputs.Listener
        ECSContainerInstanceAutoScalingRoleARN:
          !GetAtt ECS.Outputs.ECSContainerInstanceAutoScalingRoleARN
        PortalImage:
          !Ref PortalImage

  KualiResearchService:
    Type: AWS::CloudFormation::Stack
    DependsOn: KualiDashboardService
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ecs/service-research.yaml
      Parameters:
        GlobalTag:
          !Ref GlobalTag
        Landscape:
          !Ref Landscape
        VpcId:
          !Ref VpcId
        ClusterId:
          !GetAtt ECS.Outputs.Cluster
        DesiredCount: !Ref MinClusterSize
        MaxCount: !Ref MaxClusterSize
        Listener:
          !GetAtt ALB.Outputs.Listener
        ECSContainerInstanceAutoScalingRoleARN:
          !GetAtt ECS.Outputs.ECSContainerInstanceAutoScalingRoleARN
        KcImage:
          !Ref KcImage
        EnableNewRelicAPM:
          !Ref EnableNewRelicAPM

  LifeCycleHook:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ecs/lifecycle-hook.yaml
      Parameters:
        GlobalTag:
          !Ref GlobalTag
        Landscape:
          !Ref Landscape
        Cluster:
          !GetAtt ECS.Outputs.Cluster
        ECSAutoScalingGroupName:
          !GetAtt ECS.Outputs.ECSContainerInstanceAutoScalingGroupName


Outputs:

  KualiResearchUrl:
    Description: The URL endpoint for the kuali research service
    Value:
      !Sub 
      - https://${domain}/kc
      - domain: !If 
        - CreateDnsRecord
        - !Ref HostedZoneName
        - !GetAtt ALB.Outputs.DNSName
