Description: >
  This is the primary template for building a cloud formation stack for
  an ecs service. All parameters for nested templates are set here.


Parameters:

  GlobalTag:
    Type: String
    Description: >
      A common value that all resources in this template will have prefixed to
      their name and attached as a tag to establish a bundling through naming convention.
    Default: kuali-ecs
  
  BucketName:
    Type: String
    Description: The S3 bucket kuali research cloudformation templates, config files, keys, etc. are stored
    Default: kuali-research-ec2-setup

  Landscape:
    Description: Specify a landscape (sandbox, qa, etc... )
    Type: String
    AllowedValues:
    - sb
    - ci
    - qa
    - stg
    - prod
    ConstraintDescription: >
      'This parameter is restricted to the following values:
      sb, ci, qa, stg, prod'
    Default: sb

  InstanceType:
    Type: String
    Description: What type of EC2 instance should be used for ECS hosting?
    AllowedValues:
    - t2.large
    - t2.xlarge
    - t3.large
    - t3.xlarge
    - m4.large
    - m4.xlarge
    - m5.large
    - m5.xlarge
    - c5.large
    - c5.xlarge
    ConstraintDescription: Specified instance type is not within selection list.
    Default: m4.small

  ClusterSize:
    Type: Number
    Description: How many EC2 instances are to be initially deployed as ECS hosts
      accross your cluster?
    AllowedValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    ConstraintDescription: Cluster size is limited between 1 and 10 instances.
    Default: '2'

  CoreImage:
    Type: String
    Description: 'Example: 730096353738.dkr.ecr.us-east-1.amazonaws.com/core:2001.0040'

  KcImage:
    Type: String
    Description: 'Example: 730096353738.dkr.ecr.us-east-1.amazonaws.com/coeus:2001.0040'

  PortalImage:
    Type: String
    Description: 'Example: 730096353738.dkr.ecr.us-east-1.amazonaws.com/portal:2001.0040'

  PdfImage:
    Type: String
    Description: 'Example: 730096353738.dkr.ecr.us-east-1.amazonaws.com/research-pdf:2002.0003'

  EnableNewRelicAPM:
    Type: String
    Description: Is newrelic APM to be enabled for this landscape?
    Default: "false"
    AllowedValues:
    - "true"
    - "false"
    ConstraintDescription: Enter "true" or "false" only.
    Default: "false"

  EnableNewRelicInfrastructure:
    Type: String
    Description: Is newrelic infrastructure (with logging) to be enabled for this landscape?
    Default: "false"
    AllowedValues:
    - "true"
    - "false"
    ConstraintDescription: Enter "true" or "false" only.
    Default: "false"


Resources:

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ecs/vpc.yaml
      Parameters:
        Landscape:
          !Ref Landscape
        GlobalTag:
          !Ref GlobalTag

  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ecs/security-group.yaml
      Parameters:
        Landscape:
          !Ref Landscape
        GlobalTag:
          !Ref GlobalTag
        vpcid: 
          !GetAtt VPC.Outputs.VPC

  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ecs/alb.yaml
      Parameters:
        Landscape:
          !Ref Landscape
        GlobalTag:
          !Ref GlobalTag
        vpcid: 
          !GetAtt VPC.Outputs.VPC
        Subnets: 
          !GetAtt VPC.Outputs.PublicSubnets
        SecurityGroup: 
          !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup

  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ecs/cluster.yaml
      Parameters:
        Landscape:
          !Ref Landscape
        GlobalTag:
          !Ref GlobalTag
        vpcid:
          !GetAtt VPC.Outputs.VPC
        InstanceType:
          !Ref InstanceType
        ClusterSize:
          !Ref ClusterSize
        Subnets:
          !GetAtt VPC.Outputs.PrivateSubnets
        SecurityGroup:
          !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
        LoadBalancerUrl:
          !GetAtt ALB.Outputs.LoadBalancerUrl
        EnableNewRelicInfrastructure:
          !Ref EnableNewRelicInfrastructure

  KualiCoreService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ecs/service-core.yaml
      Parameters:
        GlobalTag:
          !Ref Landscape
        Landscape:
          !Ref Landscape
        vpcid:
          !GetAtt VPC.Outputs.VPC
        clusterid:
          !GetAtt ECS.Outputs.Cluster
        DesiredCount: '2'
        MaxCount: '3'
        KualiResearchUrl:
          !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "kc" ] ]
        KualiDashboardUrl:
          !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "dashboard" ] ]
        Listener80:
          !GetAtt ALB.Outputs.Listener80
        Listener443:
          !GetAtt ALB.Outputs.Listener443
        Path: "/"
        ECSServiceAutoScalingRoleARN:
          !GetAtt ECS.Outputs.ECSServiceAutoScalingRole
        CoreImage:
          !Ref CoreImage

  KualiResearchService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ecs/service-research.yaml
      Parameters:
        GlobalTag:
          !Ref Landscape
        Landscape:
          !Ref Landscape
        vpcid:
          !GetAtt VPC.Outputs.VPC
        clusterid:
          !GetAtt ECS.Outputs.Cluster
        DesiredCount: '2'
        MaxCount: '3'
        KualiCoreUrl:
          !GetAtt ALB.Outputs.LoadBalancerUrl
        KualiDashboardUrl:
          !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "dashboard" ] ]
        Listener80:
          !GetAtt ALB.Outputs.Listener80
        Listener443:
          !GetAtt ALB.Outputs.Listener443
        Path: "/kc"
        ECSServiceAutoScalingRoleARN:
          !GetAtt ECS.Outputs.ECSServiceAutoScalingRole
        KcImage:
          !Ref KcImage
        EnableNewRelicAPM:
          !Ref EnableNewRelicAPM

  KualiDashboardService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ecs/service-dashboard.yaml
      Parameters:
        GlobalTag:
          !Ref Landscape
        Landscape:
          !Ref Landscape
        vpcid:
          !GetAtt VPC.Outputs.VPC
        clusterid:
          !GetAtt ECS.Outputs.Cluster
        DesiredCount: '2'
        MaxCount: '3'
        KualiCoreUrl:
          !GetAtt ALB.Outputs.LoadBalancerUrl
        KualiResearchUrl:
          !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "kc" ] ]
        Listener80:
          !GetAtt ALB.Outputs.Listener80
        Listener443:
          !GetAtt ALB.Outputs.Listener443
        Path: "/dashboard"
        ECSServiceAutoScalingRoleARN:
          !GetAtt ECS.Outputs.ECSServiceAutoScalingRole
        PortalImage:
          !Ref PortalImage

  KualiPdfService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ecs/service-pdf.yaml
      Parameters:
        GlobalTag:
          !Ref Landscape
        Landscape:
          !Ref Landscape
        vpcid:
          !GetAtt VPC.Outputs.VPC
        clusterid:
          !GetAtt ECS.Outputs.Cluster
        DesiredCount: '2'
        MaxCount: '3'
        KualiCoreUrl:
          !GetAtt ALB.Outputs.LoadBalancerUrl
        KualiResearchUrl:
          !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "kc" ] ]
        Listener80:
          !GetAtt ALB.Outputs.Listener80
        Listener443:
          !GetAtt ALB.Outputs.Listener443
        Path: "/pdf"
        ECSServiceAutoScalingRoleARN:
          !GetAtt ECS.Outputs.ECSServiceAutoScalingRole
        PdfImage:
          !Ref PdfImage

  LifeCycleHook:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub https://s3.amazonaws.com/${BucketName}/cloudformation/kuali_ecs/lifecycle-hook.yaml
      Parameters:
        Cluster:
          !GetAtt ECS.Outputs.Cluster
        ECSAutoScalingGroupName:
          !GetAtt ECS.Outputs.ECSAutoScalingGroupName


Outputs:

  KualiCoreUrl:
    Description: The URL endpoint for the kuali cor-main service
    Value: !GetAtt ALB.Outputs.Listener

  KualiResearchUrl:
    Description: The URL endpoint for the kuali research service
    Value: 
      !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "kc" ] ]

  KualiDashboardUrl:
    Description: The URL endpoint for the kuali research service
    Value: 
      !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "dashboard" ] ]
