Description: >
  This is the primary template for building a cloud formation stack for
  an ecs service. All parameters for nested templates are set here.


Parameters:

  Landscape:
    Description: Specify a landscape (sandbox, qa, etc... )
    Type: String
    AllowedValues:
    - sb
    - ci
    - qa
    - stg
    - prod
    ConstraintDescription: >
      'This parameter is restricted to the following values:
      sb, ci, qa, stg, prod'
    Default: sb

  InstanceType:
    Type: String
    Description: What type of EC2 instance should be used for ECS hosting?
    AllowedValues:
    - t2.medium
    - t2.large
    - t2.xlarge
    - m4.small
    - m4.medium
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m5.large
    - m5.xlarge
    - m5.2xlarge
    ConstraintDescription: Specified instance type is not within selection list.
    Default: m4.small

  ClusterSize:
    Type: Number
    Description: How many EC2 instances are to be initially deployed as ECS hosts
      accross your cluster?
    AllowedValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    ConstraintDescription: Cluster size is limited between 1 and 10 instances.
    Default: '2'

  MavenVersion:
    Type: String
    Description: >
      'The maven verion number for the kuali-research application that
      is to be deployed to the cluster. Example: 1812.0024. This also happens to be
      how all other modules (core, coi, etc.) that run along with kuali-research are
      tagged as docker images in the elastic container registry. Using this value
      is how we select the correct images from the registry for each ecr task being
      deployed in a service throughout the cluster.'
    Default: '1906.0021'


Resources:

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/kuali-research-ec2-setup/cloudformation/kuali_ecs/vpc.yaml
      Parameters:
        Landscape:
          !Ref Landscape
        GlobalPrefix:
          !Ref AWS::StackName

  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/kuali-research-ec2-setup/cloudformation/kuali_ecs/security-group.yaml
      Parameters:
        Landscape:
          !Ref Landscape
        GlobalPrefix:
          !Ref AWS::StackName
        vpcid: 
          !GetAtt VPC.Outputs.VPC

  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/kuali-research-ec2-setup/cloudformation/kuali_ecs/alb.yaml
      Parameters:
        Landscape:
          !Ref Landscape
        GlobalPrefix:
          !Ref AWS::StackName
        vpcid: 
          !GetAtt VPC.Outputs.VPC
        Subnets: 
          !GetAtt VPC.Outputs.PublicSubnets
        SecurityGroup: 
          !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup

  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/kuali-research-ec2-setup/cloudformation/kuali_ecs/cluster.yaml
      Parameters:
        Landscape:
          !Ref Landscape
        GlobalPrefix:
          !Ref AWS::StackName
        vpcid:
          !GetAtt VPC.Outputs.VPC
        InstanceType:
          !Ref InstanceType
        ClusterSize:
          !Ref ClusterSize
        Subnets:
          !GetAtt VPC.Outputs.PrivateSubnets
        SecurityGroup:
          !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
        LoadBalancerUrl:
          !GetAtt ALB.Outputs.LoadBalancerUrl

  KualiCoreService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/kuali-research-ec2-setup/cloudformation/kuali_ecs/service-core.yaml
      Parameters:
        GlobalPrefix:
          !Ref Landscape
        Landscape:
          !Ref Landscape
        vpcid:
          !GetAtt VPC.Outputs.VPC
        clusterid:
          !GetAtt ECS.Outputs.Cluster
        DesiredCount: '2'
        MaxCount: '3'
        KualiResearchUrl:
          !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "kc" ] ]
        KualiDashboardUrl:
          !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "dashboard" ] ]
        Listener:
          !GetAtt ALB.Outputs.Listener
        Path: "/"
        ECSServiceAutoScalingRoleARN:
          !GetAtt ECS.Outputs.ECSServiceAutoScalingRole
        DockerImageVersion:
          !Ref MavenVersion

  KualiResearchService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/kuali-research-ec2-setup/cloudformation/kuali_ecs/service-research.yaml
      Parameters:
        GlobalPrefix:
          !Ref Landscape
        Landscape:
          !Ref Landscape
        vpcid:
          !GetAtt VPC.Outputs.VPC
        clusterid:
          !GetAtt ECS.Outputs.Cluster
        DesiredCount: '2'
        MaxCount: '3'
        KualiCoreUrl:
          !GetAtt ALB.Outputs.LoadBalancerUrl
        KualiDashboardUrl:
          !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "dashboard" ] ]
        Listener:
          !GetAtt ALB.Outputs.Listener
        Path: "/kc"
        ECSServiceAutoScalingRoleARN:
          !GetAtt ECS.Outputs.ECSServiceAutoScalingRole
        DockerImageVersion:
          !Ref MavenVersion

  KualiDashboardService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/kuali-research-ec2-setup/cloudformation/kuali_ecs/service-dashboard.yaml
      Parameters:
        GlobalPrefix:
          !Ref Landscape
        Landscape:
          !Ref Landscape
        vpcid:
          !GetAtt VPC.Outputs.VPC
        clusterid:
          !GetAtt ECS.Outputs.Cluster
        DesiredCount: '2'
        MaxCount: '3'
        KualiCoreUrl:
          !GetAtt ALB.Outputs.LoadBalancerUrl
        KualiResearchUrl:
          !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "kc" ] ]
        Listener:
          !GetAtt ALB.Outputs.Listener
        Path: "/dashboard"
        ECSServiceAutoScalingRoleARN:
          !GetAtt ECS.Outputs.ECSServiceAutoScalingRole
        DockerImageVersion:
          !Ref MavenVersion

  LifeCycleHook:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/kuali-research-ec2-setup/cloudformation/kuali_ecs/lifecycle-hook.yaml
      Parameters:
        Cluster:
          !GetAtt ECS.Outputs.Cluster
        ECSAutoScalingGroupName:
          !GetAtt ECS.Outputs.ECSAutoScalingGroupName


Outputs:

  KualiCoreUrl:
    Description: The URL endpoint for the kuali cor-main service
    Value: !GetAtt ALB.Outputs.Listener

  KualiResearchUrl:
    Description: The URL endpoint for the kuali research service
    Value: 
      !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "kc" ] ]

  KualiDashboardUrl:
    Description: The URL endpoint for the kuali research service
    Value: 
      !Join [ "/", [ !GetAtt ALB.Outputs.LoadBalancerUrl, "dashboard" ] ]
