AWSTemplateFormatVersion: 2010-09-09

Description: This service contains one task that runs the kuali pdf application

Parameters:

  GlobalTag:
    Type: String
    Description: >
      A common value that all resources in this template will have prefixed to
      their name and attached as a tag to establish a bundling through naming convention. If a nested stack,
      this will most likely be the name of the top-most stack.
    Default: kuali-ecs

  Landscape:
    Description: Specify a name for your landscape
    Type: String
    AllowedPattern: "[a-zA-Z\\d]{1,12}"
    ConstraintDescription: Up to 12 letters and/or numbers

  EnvVarFileS3Arn:
    Description: Specify the arn of a name/value pairs file in s3 for the task definition to use as environment variables for containers.
    Type: String
    AllowedPattern: "arn:aws:s3.*"

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The id of the vpc this is a subnet of.

  ClusterId:
    Type: String
    Description: Please provide the ECS Cluster ID that this service should run on

  DesiredCount:
    Type: Number
    Description: How many instances of the cor-main task should we run across our cluster?
    AllowedValues: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    ConstraintDescription: Cluster size is limited between 1 and 10 instances.
    Default: 2

  MaxCount:
    Type: Number
    Description: Maximum number of instances of the cor-main task we can run across our cluster
    AllowedValues: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    ConstraintDescription: Cluster size is limited between 1 and 10 instances.
    Default: 4
    
  Listener:
    Description: The Application Load Balancer listener to register with
    Type: String

  ECSContainerInstanceAutoScalingRoleARN:
    Type: String
    Description: The ECS service auto scaling role ARN.

  PdfImage:
    Type: String
    Description: 'Example: 770203350335.dkr.ecr.us-east-1.amazonaws.com/kuali-research-pdf:2002.0003'

  PdfS3BucketName:
    Type: String
    Description: The name of the s3 bucket the pdf service is to use.
    Default: empty

  BucketEmptierLambdaArn:
    Type: String
    Description: >-
      The arn of the lambda function used to empty the s3 bucket of waf logging content 
      during a stack delete (s3 buckets cannot be deleted unless they are empty).
    Default: empty


Conditions:
  createPdfS3Bucket: !Not [!Equals [!Ref PdfS3BucketName, empty]]
  EmptyBucket: !And [!Not [!Equals [!Ref BucketEmptierLambdaArn, empty]], Condition: createPdfS3Bucket]
  IsProd: !Equals [!Ref Landscape, prod]

    
Resources:

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Description: Definition for the Task that runs the pdf application for kuali-research
    Properties:
      Family: pdf
      NetworkMode: bridge
      RequiresCompatibilities:
      - EC2
      Volumes:
      - Name: Pdf-Config-Bind-Mount
        Host:
          SourcePath: /opt/kuali/s3/pdf/export.sh
      ContainerDefinitions:
      - Name: kuali-pdf
        User: root
        Essential: true
        Image: !Ref PdfImage
        MemoryReservation: 800
        # Environment:
        # - Name: LANDSCAPE
        #   Value:
        #     !Ref Landscape
        EnvironmentFiles:
        - Value: !Ref EnvVarFileS3Arn
          Type: s3
        PortMappings:
        - HostPort: 0
          ContainerPort: 3006
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group:
              !Ref LogGroup
            awslogs-region:
              !Ref AWS::Region
            awslogs-stream-prefix:
              !Ref AWS::StackName
            # awslogs-create-group: false
        MountPoints:
        - SourceVolume: Pdf-Config-Bind-Mount
          ContainerPath: /app/res/pdf/export.sh
          ReadOnly: true
        EntryPoint:
          - /bin/bash
          - -c
          - |
            cd /app/res/pdf
            source export.sh
            java -jar res-pdf.jar

  LogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties:
      LogGroupName:
        !Sub ${GlobalTag}-${Landscape}-pdf
      RetentionInDays: !If [ IsProd, 365, 30 ]

  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      ServiceName:
        kuali-pdf
      Cluster:
        !Ref ClusterId
      DeploymentController:
        Type: ECS
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 50
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      PlacementStrategies:
        - Field: instanceId
          Type: spread
      Role:
        !Ref ServiceRole
      DesiredCount:
        !Ref DesiredCount
      TaskDefinition:
        !Ref TaskDefinition
      HealthCheckGracePeriodSeconds: 60
      # How this service traces back to its load balancer: Service > TargetGroup > ListenerRule > Listener > ALB
      LoadBalancers:
      - ContainerName: kuali-pdf
        ContainerPort: 3006
        TargetGroupArn:
          !Ref TargetGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name:
        !Sub ${GlobalTag}-${Landscape}-pdf
      VpcId: !Ref VpcId
      Port: 3006
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 40
      HealthCheckPath: "/pdf/health"
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 30
      HealthyThresholdCount: 2
      TargetGroupAttributes:
      - Key: stickiness.enabled
        Value: true
      - Key: stickiness.type
        Value: lb_cookie
      - Key: stickiness.lb_cookie.duration_seconds
        Value: 86400
      - Key: deregistration_delay.timeout_seconds
        Value: 60
      - Key: slow_start.duration_seconds
        Value: 0
      Tags:
      - Key: Name
        Value: 
          !Sub ${GlobalTag}-${Landscape}-pdf-targetgroup

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn:
        !Ref Listener
      Priority: 6
      Actions:
      - TargetGroupArn:
          !Ref TargetGroup
        Type: forward
      Conditions:
      - Field: path-pattern
        Values:
        - "/pdf"
        - "/pdf/*"
        - "/api/v1/pdf"
        - "/api/v1/pdf/*"

  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
       !Sub ${GlobalTag}-${Landscape}-service-pdf
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ecs.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName:
         !Sub ${GlobalTag}-${Landscape}-host-policy-pdf
        PolicyDocument:
          Statement:
          - Effect: Allow
            Resource: "*"
            Action:
            - ec2:AuthorizeSecurityGroupIngress
            - ec2:Describe*
            - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
            - elasticloadbalancing:Describe*
            - elasticloadbalancing:RegisterInstancesWithLoadBalancer
            - elasticloadbalancing:DeregisterTargets
            - elasticloadbalancing:DescribeTargetGroups
            - elasticloadbalancing:DescribeTargetHealth
            - elasticloadbalancing:RegisterTargets

  ServiceScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      ResourceId:
        !Join [ "/", [ service, !Ref ClusterId, !GetAtt Service.Name ] ]
      RoleARN:
        !Ref ECSContainerInstanceAutoScalingRoleARN
      MaxCapacity:
        !Ref MaxCount
      MinCapacity:
        !Ref DesiredCount
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  ServiceScaleOutPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName:
       !Sub ${GlobalTag}-${Landscape}-target-scale-in-policy-pdf
      PolicyType: StepScaling
      ScalingTargetId:
        !Ref ServiceScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: 3000
        MetricAggregationType: Average
        StepAdjustments:
        - MetricIntervalLowerBound: 0
          ScalingAdjustment: 1

  ServiceScaleInPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName:
       !Sub ${GlobalTag}-${Landscape}-target-scale-out-policy-pdf
      PolicyType: StepScaling
      ScalingTargetId:
        !Ref ServiceScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: 3000
        MetricAggregationType: Average
        StepAdjustments:
        - MetricIntervalUpperBound: 0
          ScalingAdjustment: -1

  CPUScaleOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:
       !Sub ${GlobalTag}-${Landscape}-scale-out-alarm-pdf
      AlarmDescription: Alarm triggered when average cpu utilization across the service exceeds 85%
      Namespace: AWS/ECS
      MetricName: CPUUtilization
      Dimensions:
      - Name: ClusterName
        Value:
          !Ref ClusterId
      - Name: ServiceName
        Value:
          !GetAtt Service.Name
      Statistic: Average
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 3
      Period: 60
      Threshold: 85
      AlarmActions:
      - !Ref ServiceScaleOutPolicy

  CUPScaleInAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName:
       !Sub ${GlobalTag}-${Landscape}-scale-in-alarm-pdf
      AlarmDescription: Alarm triggered when average cpu utilization across the service falls below 85%
      Namespace: AWS/ECS
      MetricName: CPUUtilization
      Dimensions:
      - Name: ClusterName
        Value:
          !Ref ClusterId
      - Name: ServiceName
        Value:
          !GetAtt Service.Name
      Statistic: Average
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 6
      Period: 60
      Threshold: 70
      AlarmActions:
      - !Ref ServiceScaleInPolicy

  S3BucketForPDF:
    Type: AWS::S3::Bucket
    Condition: createPdfS3Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref PdfS3BucketName
      LifecycleConfiguration:
        Rules:
        - Id: OneZoneIARule
          Status: Enabled
          ExpirationInDays: '365'
          Transitions:
            - TransitionInDays: '30'
              StorageClass: ONEZONE_IA

  # The lambda backing this custom resource will detect if a stack deletion is in progress and only then the will operate.
  # The lambdas function is to empty the s3 bucket of waf logs so that cloudformation will succeed in deleting it.
  EmptyPdfBucket:
    Type: Custom::Functions
    DependsOn: S3BucketForPDF
    Condition: EmptyBucket
    Properties:
      ServiceToken: !Ref BucketEmptierLambdaArn
      BucketName: !Ref PdfS3BucketName
      MaxKeys: 50 # Indicates how many s3 bucket items deleted at a time until the bucket is empty
      
Outputs: {}
